#!/usr/bin/env python

import os
import subprocess

thumbnail_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
gunicorn = os.path.join(thumbnail_dir, 'bin', 'gunicorn')
configuration = os.path.join(thumbnail_dir, 'src', 'server', 'gunicorn.py')

subprocess.call(['python', gunicorn, '-c', configuration, 'server:app'])
