#!/usr/bin/env python

'''
usage: monitor service_url output_filename
monitor http://127.0.0.1:5050 pdf2img.png
'''


import sys
import subprocess


INPUT_URL = 'http://www.datalogics.com/pdf/doc/pdf2img.pdf'

def monitor(argv):
    if len(argv) != 3: sys.exit(__doc__)
    service_url, output_filename = (argv[1], argv[2])
    query_string = 'imageHeight=160&inputURL={}'.format(INPUT_URL)
    request_url = '{}/?{}'.format(service_url, query_string)
    subprocess.call(['curl', '--output', output_filename, request_url])

if __name__ == '__main__':
    monitor(sys.argv)
