#!/usr/bin/python

import os
import subprocess

root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
gunicorn = os.path.join(root_dir, 'bin', 'gunicorn')

args = [gunicorn, '-b', '127.0.0.1:5000', '-w', '1', 'pdfprocess:app']
subprocess.call(args)
