#!/usr/bin/env python

import os
import subprocess

root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
gunicorn = os.path.join(root_dir, 'bin', 'gunicorn')
configuration = os.path.join(root_dir, 'src', 'pdfprocess', 'gunicorn.py')

subprocess.call([gunicorn, '-c', configuration, 'pdfprocess:app'])
