#!/usr/bin/env python

"extract package versions from buildout output to produce versions.cfg"

import fileinput

print('''\
# If you want to use a specific package version, extend the pinned-versions
# section in buildout.cfg accordingly.
#
# If git indicates that this file changed, run all our tests and push the
# new version of this file if there are no regressions.
''')

buildout_stdout = [line for line in fileinput.input()]

for line in buildout_stdout[buildout_stdout.index('[versions]\n'):]:
    print(line.rstrip())
