#!/usr/bin/env python

'pdf2img emulator'

import glob
import os
import sys

root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
requests_dir = glob.glob(os.path.join(root_dir, 'eggs', 'requests-*.egg'))[0]
sys.path[0:0] = [requests_dir, os.path.join(root_dir, 'samples', 'python')]

import pdf2img


API_KEY = 'f54ab5d8-5775-42c7-b888-f074ba892b57'
BASE_URL = 'http://127.0.0.1:5000'
VERSION = 0

pdf2img.PDF2IMG(API_KEY, VERSION, BASE_URL)()

