#!/usr/bin/env python

"filter buildout output to produce versions.cfg"

import fileinput

buildout_stdout = [line for line in fileinput.input()]

for line in buildout_stdout[buildout_stdout.index('[versions]\n'):]:
    print(line.rstrip())

