#!/usr/bin/env perl -w

# buggy version of samples/perl/pdf2img.pl reproduces old server bug

use HTTP::Request::Common qw(POST);
use JSON;
use LWP::UserAgent;

my $input_file = 'data/bad.pdf';

my $content = [
    'input' => [$input_file],
    'inputName' => $input_file,
    'application' => encode_json({'id' => 'id', 'key' => 'key'}),
    'options' => encode_json({'printPreview' => true})]; # sic

my $url = 'http://127.0.0.1:5000/api/0/actions/image';
my $request = POST($url, Content_Type => 'form-data', Content => $content);

my $user_agent = LWP::UserAgent->new(ssl_opts => {verify_hostname => 0});
my $response = $user_agent->request($request)->decoded_content;

my $decoded_response = decode_json($response);
my $process_code = $decoded_response->{'processCode'};

print 'ERROR: '.$process_code."\n";
print 'Error Message: '.$decoded_response->{'output'}."\n";
exit $process_code;

