#!/usr/bin/env python

"initialize Sphinx conf.py version/release"

import fileinput
from cfg import Configuration

for line in [line for line in fileinput.input()]:
    if line.startswith('version = '):
        version = '.'.join(Configuration.versions.server.split('.')[:2])
        print("version = '{}'".format(version))
    elif line.startswith('release = '):
        print("release = '{}'".format(Configuration.versions.server))
    else:
        print(line.rstrip())
